CREATE TABLE PG
(
  ID              INT unsigned NOT NULL AUTO_INCREMENT, 
  PG_NAME         VARCHAR(101) NOT NULL,                
  PRIMARY KEY     (id)                                  
);#DONE

CREATE TABLE TARGET
(
  ID              INT unsigned NOT NULL AUTO_INCREMENT,
  PG_ID           INT unsigned NOT NULL,   
  TARGET_NAME     VARCHAR(101) NOT NULL,                
  PRIMARY KEY     (id),
  FOREIGN KEY     (PG_ID)  REFERENCES PG (ID) ON DELETE CASCADE
);#WELL

CREATE TABLE OPTIONS
(
  ID              INT unsigned PRIMARY KEY AUTO_INCREMENT,
  NAME            VARCHAR(28) NOT NULL UNIQUE
);#DONE

CREATE TABLE OPTS_LVL
(
	ID              INT unsigned PRIMARY KEY AUTO_INCREMENT,
  NAME            VARCHAR(10) NOT NULL,
  OPT_ID              INT unsigned NOT NULL,
  FOREIGN KEY (OPT_ID) REFERENCES OPTIONS (ID) ON DELETE CASCADE
);#DONE

CREATE TABLE RL_LL
(
  LL_ID              INT unsigned PRIMARY KEY AUTO_INCREMENT,
  TARGET_ID          INT unsigned NOT NULL,
  LL_NAME            VARCHAR(50) NOT NULL,
  FOREIGN KEY     (TARGET_ID)  REFERENCES TARGET (ID) ON DELETE CASCADE
);#WELL

CREATE TABLE MAIN_QUERY
( 
	DATA_ID         INT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RL_LL_ID        INT unsigned NOT NULL,
	OPT_LVL_ID      INT unsigned NOT NULL,
	FOREIGN KEY   (RL_LL_ID)  REFERENCES RL_LL (LL_ID) ON DELETE CASCADE,
	FOREIGN KEY    (OPT_LVL_ID)  REFERENCES OPTS_LVL (ID) ON DELETE CASCADE 
);#WELL

CREATE TABLE RESULT_DATA
(
	DATA_ID        INT unsigned NOT NULL UNIQUE PRIMARY KEY,
	APPLIED_DATA   MEDIUMBLOB NOT NULL,
	PURE_DATA      MEDIUMBLOB NOT NULL,
	FOREIGN KEY    (DATA_ID) REFERENCES MAIN_QUERY (DATA_ID) ON DELETE CASCADE
);#WELL

CREATE TABLE TARGET_RES
(
	ID        INT unsigned NOT NULL  PRIMARY KEY AUTO_INCREMENT,
  TARGET_ID       INT unsigned NOT NULL,
	OPT_LVL_ID      INT unsigned NOT NULL,               
  SIZE            varchar(40) NOT NULL,
  FOREIGN KEY     (TARGET_ID)  REFERENCES TARGET (ID) ON DELETE CASCADE,
	FOREIGN KEY    (OPT_LVL_ID)  REFERENCES OPTS_LVL (ID) ON DELETE CASCADE 
);

CREATE ETALON_DATA
(
  RL_LL_ID        INT unsigned NOT NULL,
  ETA_DATA        MEDIUMBLOB NOT NULL,
  FOREIGN KEY   (RL_LL_ID) REFERENCES RL_LL (LL_ID) ON DELETE CASCADE
);#WELL

CREATE OPTS_DATA
(
  DATA_ID INT UNSIGNED NOT NULL,
  APPLIED)DATA MEDIUMBLOB NOT NULL,
  FOREIGN KEY    (DATA_ID) REFERENCES MAIN_QUERY (DATA_ID) ON DELETE CASCADE
);


 SELECT ID FROM (SELECT lvl.ID,lvl.NAME `LVL_NAME`,op.NAME `OPT_NAME` FROM `OPTS_LVL` lvl
INNER JOIN `OPTIONS` op ON op.ID = lvl.OPT_ID) `offmi` WHERE LVL_NAME='%s' AND OPT_NAME='%s';#DONE

SELECT 
ALTER TABLE MAIN_QUERY
ADD COLUMN  SIZE VARCHAR(40) AFTER OPT_LVL_ID;