MAKEFILE      = Makefile
RM            = rm -f
CXX           = clang++
LD            = $(CXX)
# CXX_COMPFLAGS     =
DEBUG_CLANGFLAGS = -debug-pass=Arguments
OTHER             = -lncurses
OPT_FLAG          = -O2


TARGET_T1      = RopeStrings

OBJS_T1 = \
	RopeStrings.cpp  \
	pch.cpp  \
	CRopeString.cpp  \


# .SUFFIXES :
# .SUFFIXES : .h .cpp .ll .bc
# .cpp.ll:
# 	@echo "------------------"
# 	$(RM) $*.ll
# 	$(CXX) $(CXX_COMPFLAGS) $(OTHER) $< -o $*.ll
# .ll.bc:
# 	$(RM) $*.bc
# 	opt $(OPT_FLAG) $< -o $*.bc

all: RopeStrings

RopeStrings: $(TARGET_T1)


$(TARGET_T1):  $(OBJS_T1) $(MAKEFILE)
	@echo "=================="
	$(RM) $(TARGET_T1)
	$(LD) $(OPT_FLAG) $(DEBUG_CLANGFLAGS) -o $(TARGET_T1) $(LDFLAGS) $(OBJS_T1) $(LIBS) $(OTHER)
	@echo  " "

cleano:	        
	$(RM) $(OBJS_T0)
	$(RM) core

cleane:
	$(RM) $(TARGET_T0)

clean:	cleano cleane
# RopeStrings.ll     :$(MAKEFILE) RopeStrings.cpp
# RopeStrings.bc     :$(MAKEFILE) RopeStrings.ll
# pch.ll     :$(MAKEFILE) pch.cpp
# pch.bc     :$(MAKEFILE) pch.ll
# CRopeString.ll     :$(MAKEFILE) CRopeString.cpp
# CRopeString.bc     :$(MAKEFILE) CRopeString.ll
